version: '2'

services:
  web:
    build: ./php-apache/
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "local.edirectoryx:127.0.0.1"
    links:
      - mysql56
      - elasticsearch23

  mysql56:
    image: mysql:5.6
    mem_limit: 512M
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - TERM=xterm
    links:
      - elasticsearch23

  elasticsearch23:
    image: elasticsearch:2.3
    mem_limit: 512M
    environment:
      - TERM=xterm

